baseurl = "http://your.base.url/"
languageCode = "en-us"
title = "My HugoMDL Site"
theme = "HugoMDL"
MetaDataFormat = "yaml"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  author = "MRF regional pod ~ PTA + UKZN"
  avatar = "/images/avatar.png"
  background = "/images/jhb-night.jpg"
  description = "A place to document our MRF Regional Pod thoughts and responses" #meta description
  image = "/images/avatar-192x210.png" #for frontpage profile card
  mdlPrimary = "grey"
  mdlSecondary = "orange"
  website = "example.com"
  email = "Firstname@example.com"
  twitter = "https://twitter.com/firstname_lastname"
  github = "https://github.com/firstname_lastname/"
  linkedin = "https://linkedin.com/in/firstname_lastname/"
  facebook = "https://facebook.com/firstname_lastname/"
  copyrightyear = "2018"
  frontpageposts = 4 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"

